name: EBAC CI

on:
  push:
    branches: [ci]
    
  workflow_dispatch:
  
jobs:
  # This workflow contains a single job called "build"
  
  Tests:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install Dependencies
        run: npm install
      - name: Run k6 pretest tests
        run: npm run k6:pretest
      - name: Run k6 tests
        run: npm run k6:test
      - name: Run cypress tests
        run: npm run cy:test
      - name: Run API tests
        run: npm run jest:test
      - name: Publish Report
        uses: peaceiris/actions-gh-pages@v3
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report
